# .github/workflows/build-deb.yml
name: Build and Release Debian Package

on:
  push

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # ou adapte selon ton projet

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev debhelper

      - name: Build Debian package
        run: |
          dpkg-buildpackage -us -uc -b

      - name: Upload Debian package
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: ../*.deb