name: Release workflow

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
          
      - name: Release ITSM-ng
        run: |
          rm -r .git*
          cd /home/runner/work/itsm-workflows-bpmn
          tar -czvf itsm-workflows-bpmn-${TAG}.tgz itsm-workflows-bpmn
          mv itsm-workflows-bpmn-${TAG}.tgz /tmp

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential dpkg-dev debhelper

      - name: Build Debian package
        run: |
          sed -i 's/^VERSION *= *[0-9.]\+/VERSION = ${TAG}/' debian/rules
          dpkg-buildpackage -us -uc -b
          mv ../itsmng-workflows_${TAG}_all.deb /tmp


      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            /tmp/itsm-workflows-bpmn-${{ github.ref_name }}.tgz
            /tmp/itsmng-workflows_${{ github.ref_name }}_all.deb
          body: "New release is available"
          name: ITSM-NG ${{ github.ref_name }}
          draft: true
          generate_release_notes: true
